version: "3"
services:

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: 2GVej3IauGl5
      POSTGRES_USER: wiki
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
services:
  git:
    image: wiki:latest
    container_name: wiki
    build: .
    command: git -C /build clone https://github.com/spollacs/wikijs.git
    volumes:
      - ./build:/build

volumes:
  db-data:
