version: "3"
services:

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: 2GVej3IauGl5
      POSTGRES_USER: wiki
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wiki
      DB_PASS: 2GVej3IauGl5
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "30000:3000"

volumes:
  db-data:
